### ISSUE TITLE
The link for onboarding Software goes to Services

### ISSUE THREAD

**Issue by TalhakhanIBM** [ibm-cloud-docs/sell#2]
@mekaufman 
The link for Software 
<img width="1070" alt="Screenshot 2023-04-19 at 12 55 25 PM" src="https://user-images.githubusercontent.com/131281282/233159824-e664d9e9-bf45-45ca-bc03-4e964f80dfb2.png">

Currently goes to the services link. We need to replace this link with this one
https://cloud.ibm.com/docs/sell?topic=sell-sw-getting-started

**Comment by TalhakhanIBM** [comment]
The Partner Plus team currently sends all gold Build partners to this link https://cloud.ibm.com/docs/sell?topic=sell-selling-clouds

So folks wanting to onboard BYOL will be confused. That being said Gold partners all have 100k ESA commits so they should onboard Saas. 

Still should fix the links.

**Comment by cairey81** [comment]
@TalhakhanIBM Thank you for the feedback! 
I've pushed a change to fix the link, and I've opened an internal issue to discuss your second comment.
