### ISSUE TITLE
Change Direct ESA verbiage to just ESA

### ISSUE THREAD

**Issue by TalhakhanIBM** [ibm-cloud-docs/sell#3]
<img width="1018" alt="Screenshot 2023-04-19 at 1 02 20 PM" src="https://user-images.githubusercontent.com/131281282/233161362-0722832b-de34-4d6a-9eae-39c1a8070a54.png">

The verbiage says 
To sell services, verify that your company is an approved IBM Cloud build partner with a [Direct Embedded Solutions Agreement](https://www-2000.ibm.com/partnerworld/pdfs/IBM_ESA_Technology_Partner_Direct_Application_Guide.pdf). For more information about being an IBM Cloud build partner, see the [IBM Build Partner](https://www.ibm.com/partnerworld/public/build) page.

We need to change the verbiage to say "build partner with an Embedded Solutions Agreement.
Partners can onbaord to the catalog if they have an ESA through a Tech Broker. 
I think we can keep the link because we have a perogative to give IBM Sellers deals by sending folks to the Direct ESA link but we dont exclude folks with a tech broker cloud esa from onboarding.

**Comment by cairey81** [comment]
@TalhakhanIBM Thank you for the feedback! I've opened an internal issue that we'll use to track this feedback.
