### ISSUE TITLE
Changes to metering page

### ISSUE THREAD

**Issue by TalhakhanIBM** [ibm-cloud-docs/sell#4]
Hey team. Our metering docs need to match our UI better. I'm proposing the following changes.
Here's a Pic of our UI and what we offer just for reference:
<img width="1536" alt="Screenshot 2023-06-06 at 3 24 22 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/084b60e1-c202-4370-8d5a-f2d1b2d151f1">

Add into the end of the "Unit" section the verbiage:
"You are also capable of creating custom metrics of your choosing however they must abide by the metering models currently available."

<img width="998" alt="Screenshot 2023-06-06 at 3 27 58 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/a14aacbb-d5fa-4dab-beee-90b4761846c9">

Lets take out any mention of Standard Max and Daily proration avg as they're not even an option in the UI
<img width="1018" alt="Screenshot 2023-06-06 at 3 27 03 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/2efac5fd-72ed-4393-9bb4-0679d8a0507e">

Cut these two sections.
<img width="1010" alt="Screenshot 2023-06-06 at 3 29 33 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/3b6976b1-7555-46ef-b8a2-fdd6a658431f">
<img width="1021" alt="Screenshot 2023-06-06 at 3 29 44 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/9dee42b8-d00b-4296-9f7b-4156e2c28dbc">

And add in verbiage to the bottom note saying :
"We currently offer Graduated Tier to a select few partners and are not accepting new partners at this time"
More or less this isn't a capability in the platform but we've given it to 1 ISV because they were...persistent. 
<img width="913" alt="Screenshot 2023-06-06 at 3 30 08 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/92ffc1b5-6140-476c-b32a-20bab3e94629">

@mekaufman @

**Comment by TalhakhanIBM** [comment]
Adding to this change that we need to add a note under monthly proration saying 
"Note: As part of Monthly Proration, the "end" event_time that you submit is the first day that customers will be billed and all days following that day in the month will be billed as well. "end" acts similar to "start" in this case and should be the same values."

@mekaufman 
<img width="940" alt="Screenshot 2023-07-13 at 1 16 15 PM" src="https://github.com/ibm-cloud-docs/sell/assets/131281282/978ea72f-a56e-4752-9d45-a77a63ebc07f">

**Comment by hooznora** [comment]
Hey @TalhakhanIBM,
As discussed, the suggestions that you provided in this issue have been moved to an internal documentation issue. Closing this public issue.
