### ISSUE TITLE
Partners keep getting stuck on creating IAM Token

### ISSUE THREAD

**Issue by emanuel-ibarra** [ibm-cloud-docs/sell#5]
Partners are required to generate an IAM token using their ServiceID, but have to go through three docs to figure out how. We need to add that in metering integration doc.

https://cloud.ibm.com/docs/sell?topic=sell-service-add-metrics#create-metering-json

Here is the instructions that the need: https://cloud.ibm.com/apidocs/iam-identity-token-api#gettoken-apikey

**Comment by mekaufman** [comment]
@emanuel-ibarra Thanks. I've reached out and we'll get this addressed.
